version: "3"

services:
  todo-cli-db:
    image: postgres:latest
    container_name: todo-cli-db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: todo-cli
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  todo-cli:
    build: .
    container_name: todo-cli
    volumes:
      - .:/go/src
